name: C/C++ CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build​
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]
        host: [ubuntu-latest, macos-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: test_deps
      run: if [ "${OS}" = "macos-latest" ]; then brew install check; else sudo apt-get install check; fi
      env:
        OS: ${{ matrix.host }}

    - name: configure
      run: echo "${CC} -O2 -fPIC -Wall -Wshadow -Werror=implicit-function-declaration" > conf-cc
      env:
        CC: ${{ matrix.cc }}

    - name: make
      run: make it man

    - name: unittests
      run: make test
